### ISSUE TITLE
[ERROR] unable to load plugin [jello-hook-amd] or [fis3-hook-amd] or [fis-hook-amd]

### ISSUE THREAD

**Issue by codingtiger** [fis-scaffold/jello-demo#1]
系统环境：
OS X 10.10.5

java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

npm version:
2.10.1

搭建jello-demo步骤如下：

```
sudo npm install -g fis3@3.2.1
sudo npm install -g fis3-jello
sudo fis3 init jello-demo
fis3 release
```

报错如下：

[INFO] Currently running fis3 (/usr/local/lib/node_modules/fis3/)

 δ 3ms

 Ω
 [ERROR] unable to load plugin [jello-hook-amd] or [fis3-hook-amd] or [fis-hook-amd]

**Comment by 2betop** [comment]
你改为全局安装了啊？没事补上 

```
sudo npm install -g fis3-hook-amd
```

**Comment by codingtiger** [comment]
还有以下几个问题：
1、
jello-hook-amd
fis-hook-amd
这俩个插件在https://www.npmjs.com
上面搜索不到，与fis3-hook-amd这三者是什么关系。

2、第二次启动报错变化了
 [ERROR] unable to load plugin [jello-parser-marked] or [fis3-parser-marked] or [fis-parser-marked]
安装fis-parser-marked插件之后，可以正常执行了。为啥俩次执行的结果还不一样了呢？

**Comment by 2betop** [comment]
fis 会按顺序尝试加载 `fis-hook-amd`，`fis3-hook-amd` 和 `jello-hook-amd` 如果都找不到，就会报错。

实际上插件只有一个 `fis3-hook-amd` ,  fis  打头的插件，面上的是说有 fis 解决方案， fis3  打头的是只有 fis3 能用， jello 也就是只有 jello 下才有用的。jello 有共用 fis 和 fis3 的插件，所以用插件的时候，需要留意下到底是哪个前缀下的存在。
