### ISSUE TITLE
org.apache.velocity.exception.ResourceNotFoundException: Unable to find resource 'xxx.vm'

### ISSUE THREAD

**Issue by codingtiger** [fis-scaffold/jello-demo#2]
vm文件中使用#include("xxx.vm")指令，使用相对路径不能定位到对应的资源。
放置在同一目录下，也不能定位到路径。
请问是有什么特殊的配置？还是只能使用扩展标签widget？

**Comment by 2betop** [comment]
jello 里面并没有扩展对 include 路径的支持，所以，是的，只能用 widget.

**Comment by codingtiger** [comment]
thx.
