### ISSUE TITLE
server.conf文件不生效

### ISSUE THREAD

**Issue by MarvinXu** [fis-scaffold/jello-demo#8]
- /
  static
  test
  WEB-INF

fis3 release之后只显示如上的目录结构，不显示首页。检查了一下server.conf文件，发现在WEB-INF下，变成了server-.conf

**Comment by alpar** [comment]
试试 fis3 server start --type jello

**Comment by MarvinXu** [comment]
嗯 发现了这个  谢谢~

**Comment by cfanlu** [comment]
请问解决了么,应该是fis3 release的问题吧

**Comment by MarvinXu** [comment]
解决了，是start server的类型不对，我的项目是jello项目，但是开启的是node服务器，应该显式指明服务器类型 --type jello
